version: 1
config:
  - type: nameserver
    address:
      - 8.8.8.8
      - 8.8.4.4
  - type: physical
    name: enp0s3
    subnets:
     - control: auto
       type: static
       address: 192.168.122.48/24
       gateway: 192.168.122.1
